#![allow(non_camel_case_types, non_snake_case)]
#![doc(html_root_url = "https://docs.rs/nvapi-sys/0.2.0")]

#[macro_use]
mod macros;

pub mod nvapi;
pub mod nvid;
pub mod status;
pub mod types;

/// NVAPI Handles - These handles are retrieved from various calls and passed in
/// to others in NvAPI These are meant to be opaque types. Do not assume they
/// correspond to indices, HDCs, display indexes or anything else.
///
/// Most handles remain valid until a display re-configuration (display mode set)
/// or GPU reconfiguration (going into or out of SLI modes) occurs. If
/// NVAPI_HANDLE_INVALIDATED is received by an app, it should discard all
/// handles, and re-enumerate them.
pub mod handles;

/// The display driver APIs are used to retrieve information about the display driver.
pub mod driverapi;

pub mod sysgeneral;

/// Video Input Output (VIO) API
pub mod vidio;

/// The GPU APIs retrieve and control various attributes of the GPU, such as outputs, VBIOS revision, APG rate, frame buffer size, and thermal settings.
pub mod gpu;

/// Sync Display APIs
pub mod gsync;

/// I2C API - Provides ability to read or write data using I2C protocol.
/// These APIs allow I2C access only to DDC monitors
pub mod i2c;

#[cfg(windows)]
pub mod dx;

pub mod dispcontrol;

pub use nvapi::nvapi_QueryInterface;
pub use nvid::Api;
pub use status::{NvAPI_Status, Status};
pub use types::*;

use std::convert::Infallible;
use std::error::Error as StdError;
use std::{fmt, result};

pub mod api {
    pub use self::private::*;
    pub use crate::driverapi::*;
    #[cfg(windows)]
    pub use crate::dx::*;
    pub use crate::gpu::clock::*;
    pub use crate::gpu::cooler::*;
    pub use crate::gpu::display::*;
    pub use crate::gpu::ecc::*;
    pub use crate::gpu::illumination::*;

    pub use crate::gpu::pstate::*;
    pub use crate::gpu::thermal::*;
    pub use crate::gpu::*;
    pub use crate::gsync::*;
    pub use crate::handles::*;
    pub use crate::i2c::*;
    pub use crate::nvapi::*;
    pub use crate::sysgeneral::*;
    pub use crate::vidio::*;

    pub mod private {
        pub use crate::driverapi::private::*;
        pub use crate::gpu::clock::private::*;
        pub use crate::gpu::cooler::private::*;
        pub use crate::gpu::power::private::*;
        pub use crate::gpu::private::*;
        pub use crate::gpu::pstate::private::*;
        pub use crate::gpu::thermal::private::*;
        pub use crate::i2c::private::*;
    }
}

pub(crate) mod prelude_ {
    pub(crate) use crate::handles::{self, NvPhysicalGpuHandle};
    pub(crate) use crate::nvapi::NvVersion;
    pub(crate) use crate::status::NvAPI_Status;
    pub(crate) use crate::types::*;
    pub(crate) type Array<T> = Padding<T>;
}

/// The result of a fallible NVAPI call.
pub type Result<T> = result::Result<T, Status>;

/// Treat `NVAPI_OK` as `Ok(())` and all else as an `Err(..)`.
pub fn status_result(status: NvAPI_Status) -> Result<()> {
    match status {
        status::NVAPI_OK => Ok(()),
        status => Err(Status::from_raw(status).unwrap_or(Status::Error)),
    }
}

/// Error type indicating a raw value is out of the range of known enum values.
#[derive(Debug, Copy, Clone, Default)]
pub struct ArgumentRangeError;

impl fmt::Display for ArgumentRangeError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("received data out of range")
    }
}

impl StdError for ArgumentRangeError {}

impl From<ArgumentRangeError> for Status {
    fn from(_: ArgumentRangeError) -> Self {
        Status::ArgumentExceedMaxSize
    }
}

impl From<Infallible> for ArgumentRangeError {
    fn from(e: Infallible) -> Self {
        match e {}
    }
}

/// When the `log` feature is enabled, every FFI function generated by `nvapi!`
/// emits a `log::trace!` at target `nvapi_sys::api` recording the `Api` enum
/// variant and the returned status. This test installs a capturing logger and
/// confirms the instrumentation fires on a real call (regardless of whether a
/// driver is present — the call still goes through the macro body).
#[cfg(all(test, feature = "log"))]
mod log_tests {
    use std::sync::atomic::{AtomicBool, Ordering};

    static HIT: AtomicBool = AtomicBool::new(false);

    struct CapturingLogger;

    impl log::Log for CapturingLogger {
        fn enabled(&self, metadata: &log::Metadata) -> bool {
            metadata.target() == "nvapi_sys::api"
        }

        fn log(&self, record: &log::Record) {
            if self.enabled(record.metadata()) {
                HIT.store(true, Ordering::SeqCst);
            }
        }

        fn flush(&self) {}
    }

    #[test]
    fn nvapi_macro_emits_log_trace() {
        // Install our capturing logger. If a logger is already set this fails —
        // tests run in a single process so the first install wins; reset HIT first.
        HIT.store(false, Ordering::SeqCst);
        let _ = log::set_logger(&CapturingLogger);
        log::set_max_level(log::LevelFilter::Trace);

        // NvAPI_Initialize is cheap and always present in the macro surface.
        // Whether it succeeds or not, the `nvapi!` body runs and should log.
        let _status = unsafe { crate::nvapi::NvAPI_Initialize() };

        // Restore so we don't poison other tests' logging.
        log::set_max_level(log::LevelFilter::Off);

        assert!(
            HIT.load(Ordering::SeqCst),
            "expected an `nvapi_sys::api` trace log from NvAPI_Initialize, got none"
        );
    }
}

